#!/usr/bin/env python3
"""Convert a captured accelerometer CSV into an embedded C array for
accel_synthetic.c.

Renode has no model for either onboard accelerometer chip (LIS3DSH/
LIS302DL), so the Renode build of this firmware (the "stm32-renode" CMake
preset, ACCEL_SOURCE=synthetic) substitutes a CSV-derived X/Y/Z sample array
in place of real SPI reads -- see ../src/accel_synthetic.c. This script
produces that array from any CSV in the format tools/uart_capture.py writes
(an optional leading "#" comment line, a "sample_num,x,y,z" header, then one
row per sample) -- so a capture taken from real hardware can be replayed
later under Renode, unmodified.

Usage:
    python3 tools/csv_to_c_array.py capture.csv \\
        --output src/generated/synthetic_accel_data.h

    # Re-generate the committed default from the bundled reference capture:
    python3 tools/csv_to_c_array.py testdata/sample_capture.csv \\
        --output src/generated/synthetic_accel_data.h
"""

import argparse
import csv
import sys


def load_samples(path):
    samples = []
    with open(path, newline="") as f:
        for row in csv.reader(f):
            if not row or row[0].startswith("#"):
                continue
            if row[0] == "sample_num":
                continue  # header row
            if len(row) < 4:
                continue
            _, x, y, z = row[0], row[1], row[2], row[3]
            samples.append((int(x), int(y), int(z)))
    return samples


def write_header(path, samples, source_name):
    with open(path, "w") as f:
        f.write("/* Auto-generated by tools/csv_to_c_array.py -- do not hand-edit.\n")
        f.write(f" * Source CSV: {source_name}\n")
        f.write(f" * {len(samples)} X/Y/Z samples in mg.\n")
        f.write(" */\n\n")
        f.write("#ifndef SYNTHETIC_ACCEL_DATA_H\n")
        f.write("#define SYNTHETIC_ACCEL_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define SYNTHETIC_ACCEL_LEN {len(samples)}u\n\n")
        f.write("/* Row i = { x_mg, y_mg, z_mg } for sample i. */\n")
        f.write("static const int16_t synthetic_accel_mg[SYNTHETIC_ACCEL_LEN][3] = {\n")
        for x, y, z in samples:
            f.write(f"    {{ {x}, {y}, {z} }},\n")
        f.write("};\n\n")
        f.write("#endif /* SYNTHETIC_ACCEL_DATA_H */\n")


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("input", help="Captured CSV to embed (as written by tools/uart_capture.py)")
    p.add_argument("--output", default="src/generated/synthetic_accel_data.h",
                    help="Output header path (default: src/generated/synthetic_accel_data.h)")
    args = p.parse_args()

    samples = load_samples(args.input)
    if not samples:
        sys.exit(f"No samples found in {args.input} -- check the file is in "
                  "uart_capture.py's CSV format.")

    write_header(args.output, samples, args.input)
    print(f"Wrote {len(samples)} samples to {args.output}")
    print("Rebuild the Renode firmware to pick it up:")
    print("  cmake --build --preset stm32-renode")


if __name__ == "__main__":
    main()
