/* accel_synthetic.c -- CSV-derived stand-in for the real SPI accelerometer
 * driver, used only by the "stm32-renode" build (see ../CMakeLists.txt's
 * ACCEL_SOURCE option and ../CMakePresets.json).
 *
 * Renode has no model for either onboard accelerometer chip (LIS3DSH/
 * LIS302DL), so this file implements the same accel_init()/accel_name()/
 * accel_read_mg() interface declared in accel.h (see that file) by looping
 * a CSV-derived X/Y/Z array embedded at build time (generated by
 * ../tools/csv_to_c_array.py from any capture produced by
 * ../tools/uart_capture.py -- run it against a real capture to change the
 * compiled-in default). main.c is unaware which implementation it is
 * linked against, and touches no SPI1/GPIOE hardware in this build.
 *
 * Unlike the PDM-audio Renode demo this project's build system is modeled
 * on (../../stm32f4_audio_examples/audio_in_to_wav), no self-paced timing
 * trick is needed here: main.c's own capture loop already blocks on
 * SysTick between samples (200 ms/sample), so accel_read_mg() only needs
 * to hand back the next row -- looping back to the start once the embedded
 * array is exhausted.
 *
 * The array is a fixed-capacity buffer (its compiled-in size is
 * SYNTHETIC_ACCEL_LEN, the maximum number of distinct samples this
 * firmware.elf can ever replay before looping), but the loop length is a
 * separate, non-const, individually-addressable global, synthetic_accel_len.
 * ../renode/accel_demo.resc resolves both symbols' addresses via
 * `sysbus GetSymbolAddress` and overwrites them in-place (`sysbus
 * LoadBinary` + `sysbus WriteDoubleWord`) right after `sysbus LoadELF`,
 * before `start` -- this lets a single compiled firmware.elf replay any
 * captured CSV (up to the compiled-in capacity) selected at Renode
 * invocation time, with no rebuild. See ../tools/csv_to_bin.py for the
 * host-side CSV conversion this relies on, and the "Renode" section of
 * ../README.md for usage. */

#include "accel.h"
#include "hal.h"
#include "generated/synthetic_accel_data.h"
#include <stddef.h>

/* Loop length in samples, <= SYNTHETIC_ACCEL_LEN. Not const/static so it
 * has a stable, discoverable ELF symbol (see file comment above) -- defaults
 * to the full compiled-in array, so the demo behaves exactly as before if
 * nothing pokes it. */
volatile uint32_t synthetic_accel_len = SYNTHETIC_ACCEL_LEN;

static uint32_t read_idx;

const char *accel_name(accel_t chip)
{
    (void)chip;
    return "SYNTHETIC";
}

accel_t accel_init(void)
{
    uart_puts("Chip: SYNTHETIC  (");
    uart_print_int((int32_t)SYNTHETIC_ACCEL_LEN);
    uart_puts(" samples embedded, CSV-derived, no SPI hardware)\r\n");
    return ACCEL_SYNTHETIC;
}

void accel_read_mg(accel_t chip, int32_t *mx, int32_t *my, int32_t *mz)
{
    (void)chip;
    uint32_t n = synthetic_accel_len ? synthetic_accel_len : 1U;
    uint32_t i = read_idx % n;
    *mx = synthetic_accel_mg[i][0];
    *my = synthetic_accel_mg[i][1];
    *mz = synthetic_accel_mg[i][2];
    read_idx = (i + 1U) % n;
}
